version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
    networks:
      - my-network

  python-app:
    image: etl-challenge:latest
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge